"""Structural tests for the 24h dnd-llm corpus supplement.

The 24h supplement (cases_24h.json + cases_24h_negative.json) was
generated by:
  1. scripts/extract_dnd_24h_candidates.py — pull all user msgs from
     dnd-llm transcripts modified in the last 24h.
  2. agent classifier (general-purpose subagent) → candidates_24h_classified.json
  3. MANUAL VETTING → vetted_24h.json (drop auto-injected noise:
     session-continuation summaries, Stop hook reactivation banners,
     "Continue from where you left off"; override classifier mislabels;
     drop low-confidence borderline cases)
  4. scripts/build_dnd_24h_cases.py → cases_24h.json + cases_24h_negative.json

These tests are pure structure; the live baseline lives in commit
messages / scratchpad, not as a CI gate (the negative corpus
intentionally over-fires under the current rubric — see commit message
for the recon_as_work calibration discussion).
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
FIX = ROOT / "tests" / "fixtures" / "wrong_level_corpus"
POS = FIX / "cases_24h.json"
NEG = FIX / "cases_24h_negative.json"
VETTED = FIX / "vetted_24h.json"
CANDIDATES = FIX / "candidates_24h.json"


@pytest.fixture(scope="module")
def positives() -> list[dict]:
    assert POS.is_file()
    return json.loads(POS.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def negatives() -> list[dict]:
    assert NEG.is_file()
    return json.loads(NEG.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def vetted() -> list[dict]:
    assert VETTED.is_file()
    return json.loads(VETTED.read_text(encoding="utf-8"))


# --- Counts roughly match expectations ------------------------------------


def test_positives_count_matches_vetted(positives, vetted):
    expected = sum(1 for v in vetted if v["label"] == "PUSHBACK")
    assert len(positives) == expected, (
        f"positives count {len(positives)} != vetted PUSHBACKs {expected}"
    )


def test_negatives_count_matches_vetted(negatives, vetted):
    expected = sum(1 for v in vetted if v["label"] == "CLEAN")
    assert len(negatives) == expected, (
        f"negatives count {len(negatives)} != vetted CLEANs {expected}"
    )


def test_no_auto_injected_noise_leaked(positives, negatives):
    """Vetting excluded session-continuation summaries, Stop hook
    banners, and resume artifacts. Any case carrying one of those
    user_texts means the vetting filter was bypassed."""
    NOISE_FRAGMENTS = (
        "This session is being continued from a previous conversation",
        "A session-scoped Stop hook is now active",
        "Continue from where you left off",
    )
    for c in positives + negatives:
        ack = c["ack_excerpt"]
        for frag in NOISE_FRAGMENTS:
            assert frag not in ack, (
                f"{c['case_id']} carries auto-injected text: {frag!r}"
            )


# --- Schema -----------------------------------------------------------------


_REQUIRED_TOP = {
    "case_id", "cwd", "session_id", "tool_name", "tool_input",
    "tool_response", "expected", "mode", "ack_excerpt", "session_context",
}


def test_positives_schema(positives):
    for c in positives:
        missing = _REQUIRED_TOP - set(c.keys())
        assert not missing, f"{c['case_id']} missing: {missing}"
        assert c["mode"] == "wrong_level_positive"
        assert c["expected"]["professional"] is False
        # Positives must point to a real drift_kind for the question lookup.
        from gadfly.prompts import TRAIL_DRIFT_QUESTIONS
        kind = c["expected"]["drift_kind_primary"]
        assert kind in TRAIL_DRIFT_QUESTIONS, (
            f"{c['case_id']} primary {kind!r} not in TRAIL_DRIFT_QUESTIONS"
        )


def test_negatives_schema(negatives):
    for c in negatives:
        missing = _REQUIRED_TOP - set(c.keys())
        assert not missing, f"{c['case_id']} missing: {missing}"
        assert c["mode"] == "wrong_level_negative"
        # Negatives don't carry drift_kind_primary — success = silence.
        assert c["expected"]["professional"] is True


def test_recent_actions_not_empty(positives, negatives):
    """Trail rubric needs ≥1 prior action. Cases with empty trails are
    fixture bugs — they wouldn't exercise the longitudinal logic."""
    for c in positives + negatives:
        n = len(c["session_context"]["recent_actions"])
        assert n >= 1, f"{c['case_id']} has 0 recent_actions"


def test_ack_excerpt_is_real_user_text(positives, negatives):
    """`ack_excerpt` is the verbatim user message that came AFTER the
    trigger action — it's what the case is ABOUT. The slice deliberately
    ends BEFORE this message so the rubric is asked 'would you flag the
    trajectory leading up to this?' rather than 'do you agree with the
    user?'. So ack_excerpt is NOT expected to live inside
    session_context.recent_user_requests."""
    for c in positives + negatives:
        ack = c["ack_excerpt"]
        assert isinstance(ack, str) and ack.strip(), c["case_id"]
        # Cap at 400c by the builder.
        assert len(ack) <= 400, c["case_id"]


def test_session_context_carries_some_user_requests(positives, negatives):
    """The slice always ends after at least one user-role entry (even if
    that entry is a session-continuation summary). Sessions with no
    user_requests at all would mean the slice is corrupt."""
    for c in positives + negatives:
        users = c["session_context"]["recent_user_requests"]
        assert users, f"{c['case_id']} has empty recent_user_requests"
